version: "3.8"

services:
  bot:
    container_name: pipisa_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sh -c scripts/entrypoint.sh
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - './postgres_data/:/var/lib/postgresql/data'
    env_file:
      - .env
    ports:
      - '5433:5432'

volumes:
  postgres_data: